--<ScriptOptions statementTerminator=";"/>
-- Version 19589

ALTER TABLE KT06_BePoLaufProg_InEx_01_WBM DROP CONSTRAINT KT06_BelPosLPro_InEx_01_WBM_FK;

ALTER TABLE KT06_BePoLaufProg_InEx_01_WBM DROP CONSTRAINT KT06_BelPosLPro_InEx_01_WBM_PK;

DROP TABLE KT06_BePoLaufProg_InEx_01_WBM;

