--<ScriptOptions statementTerminator=";"/>
-- Version 22162

CREATE TABLE MD36_SDS_Bilanz_Summensatz (
		TA_Ladedatum DATE NOT NULL,
		TA_Ersatzdatum DATE NOT NULL,
		TA_Lade_ID  NUMBER(28 , 0) NOT NULL,
		SNR2_A VARCHAR2(64 CHAR) NOT NULL,
		ZBS VARCHAR2(8 CHAR),
		AAS_A VARCHAR2(64 CHAR),
		UKZ VARCHAR2(8 CHAR),
		VNR_A VARCHAR2(64 CHAR),
		ZNR VARCHAR2(8 CHAR),
		RNR VARCHAR2(8 CHAR),
		ANK VARCHAR2(8 CHAR),
		ABW VARCHAR2(8 CHAR),
		BEM VARCHAR2(8 CHAR),
		EDA VARCHAR2(24 CHAR),
		MDA VARCHAR2(8 CHAR),
		ADS VARCHAR2(8 CHAR),
		ATV VARCHAR2(8 CHAR),
		ELA VARCHAR2(8 CHAR),
		SDA VARCHAR2(24 CHAR),
		KAS VARCHAR2(8 CHAR),
		FGJ NUMBER(16 , 2),
		KAF1 VARCHAR2(8 CHAR),
		FDA VARCHAR2(24 CHAR),
		PLZ VARCHAR2(24 CHAR),
		ZDA VARCHAR2(24 CHAR),
		REN1 NUMBER(16 , 2),
		ENT1 NUMBER(16 , 2),
		KOS1 NUMBER(16 , 2),
		REN2 NUMBER(16 , 2),
		ENT2 NUMBER(16 , 2),
		KOS2 NUMBER(16 , 2),
		RGJ NUMBER(16 , 2),
		KAR1 VARCHAR2(8 CHAR),
		VDA VARCHAR2(24 CHAR),
		RVJ NUMBER(16 , 2),
		KAR2 VARCHAR2(8 CHAR),
		RMJ NUMBER(16 , 2),
		KAR3 VARCHAR2(8 CHAR),
		DGJ NUMBER(16 , 2),
		KAD1 VARCHAR2(8 CHAR),
		DVJ NUMBER(16 , 2),
		KAD2 VARCHAR2(8 CHAR),
		DMJ NUMBER(16 , 2),
		KAD3 VARCHAR2(8 CHAR),
		RVK VARCHAR2(8 CHAR),
		FVJ NUMBER(16 , 2),
		KAF2 VARCHAR2(8 CHAR),
		FEJ NUMBER(16 , 2),
		KAF3 VARCHAR2(8 CHAR),
		LGJ VARCHAR2(8 CHAR) NOT NULL,
		LGM VARCHAR2(8 CHAR) NOT NULL,
		ADU VARCHAR2(8 CHAR),
		BKT_A VARCHAR2(64 CHAR),
		EFU VARCHAR2(8 CHAR),
		INV NUMBER(16 , 2),
		SPA VARCHAR2(2 CHAR)
	)
	PCTFREE 0
	PCTUSED 0
	LOGGING;

ALTER TABLE MD36_SDS_Bilanz_Summensatz ADD CONSTRAINT MD36_SDS_Bilanz_Summensatz_PK PRIMARY KEY
	(SNR2_A,
	 LGJ,
	 LGM,
	 TA_Ladedatum);

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.AAS_A IS
'AA DES ZUST.SACHBEARBEITERS';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ABW IS
'ABWEICHUNG VOM VERTRAGSSTAND';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ADS IS
'ART (URSACHE) DES SCHADENS';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ADU IS
'ART DES UNFALLS';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ANK IS
'ALTES/NEUES KFZ BETEILIGT';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ATV IS
'ANZAHL DER TOTEN/VERLETZTEN';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.BEM IS
'BEMERKUNG';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.BKT_A IS
'BETROFFENER KOERPERTEIL  ';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.DGJ IS
'RENTENL-RESERVE  (MJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.DMJ IS
'RENTEN-RESERVE (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.DVJ IS
'RENTEN-RESERVE (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.EDA IS
'EINTRITTS-DATUM (JJJJMMTT)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.EFU IS
'ERWEIT. FREIZEITUNFALLSCHUTZ';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ELA IS
'EINTRITTSLAND';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ENT1 IS
'ENTSCHAEDIGUNGEN (GJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ENT2 IS
'ENTSCHAEDIGUNGEN (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.FDA IS
'FORDERUNGS-DATUM (JJJJMMTT)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.FEJ IS
'FORDERUNGS-BETRAG (EJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.FGJ IS
'FORDERUNGS-BETRAG (GJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.FVJ IS
'FORDERUNGS-BETRAG (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.INV IS
'INVALIDITAETS-PROZENTSATZ ';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAD1 IS
'KLASSIF.-ART  (GJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAD2 IS
'KLASSIF.-ART  (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAD3 IS
'KLASSIF.-ART  (MJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAF1 IS
'KA DER FORDERUNG (GJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAF2 IS
'KA DER FORDERUNG (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAF3 IS
'KA DER FORDERUNG (EJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAR1 IS
'KLASSIF.-ART  (GJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAR2 IS
'KLASSIF.-ART  (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAR3 IS
'KLASSIF.-ART  (MJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KAS IS
'KLASSIFIZIERUNGS-ART ZU SDA';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KOS1 IS
'KOSTEN   (GJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.KOS2 IS
'KOSTEN   (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.LGJ IS
'LFD. GESCHAEFTSJAHR';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.LGM IS
'LFD. GESCHAEFTSMONAT';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.MDA IS
'MELDE-DATUM (MMTT)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.PLZ IS
'POSTLEITZAHL DES SCHADENORTS';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.REN1 IS
'RENTEN-ZAHLUNGEN (GJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.REN2 IS
'RENTEN-ZAHLUNGEN (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.RGJ IS
'KAPITAL-RESERVE  (GJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.RMJ IS
'KAPITAL-RESERVE  (MJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.RNR IS
'RISIKO-NR.';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.RVJ IS
'KAPITAL-RESERVE  (VJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.RVK IS
'RUECKVERSICH.-KENNZEICHEN';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.SDA IS
'SCHLUSSMELDEDATUM (JJJJMMTT)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.SNR2_A IS
'SCHADEN-NR. MIT PRUEFZIFFER

besteht aus
MJJ			CHAR  (4),     MELDE-JAHR
SPA 		CHAR  (2),     SPARTE
MBL		CHAR  (2),     MELDENDE BL
LFD			CHAR  (5),     LAUFENDE NR.
SPZ			CHAR  (1),     PRUEFZIFFER ZUR SNR
';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.SPA IS
'Spartenkennziffer, zweistellig';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.TA_Ersatzdatum IS
'Identifiziert eindeutig, wann der nächste Datensatz in die Tabelle geladen wurde, Es entspricht dem Lade-Lauf-Datum des nächsten Laufs.	date

DEFAULT: Highdate

Datenschutz $-';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.TA_Lade_ID  IS
'... ist die Identifizierung des entsprechenden Ladejobs, in dem dieser Tabellen-Eintrag geladen wurde.

Datenschutz $-';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.TA_Ladedatum IS
'... ist der Beginn (bis Minute) des jeweiligen Gesamt-Lade-Jobs, in dem auch dieser Satz vom Quellsystem ins Data Warehouse geladen wurde.
Identifiziert damit eindeutig, wann die Daten aus dem Quellsystem extrahiert wurden.

Datenschutz $-';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.UKZ IS
'UNTERNEHMENSKENNZEICHEN';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.VDA IS
'VERAENDERUNGS-DATUM (GJ)';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.VNR_A IS
'VERSICHERUNGSSCHEIN-NR.';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ZBS IS
'ZUSTAENDIGE BEARBEIT.-STELLE';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ZDA IS
'ZUSTAEND.-AENDER.-DATUM JMT';

COMMENT ON COLUMN MD36_SDS_Bilanz_Summensatz.ZNR IS
'ZUSATZ-NR.(GNR,LNR,POS)';

COMMENT ON TABLE MD36_SDS_Bilanz_Summensatz IS
'PS501 - Bestand Altdatenübernahme - in PS501: MS50201_Summensatz
Schaden-Summensätze
nur Jahresendstände';

