--<ScriptOptions statementTerminator=";"/>
-- Version 7335

ALTER TABLE KT01_Beleg_InEx_01_HBS DROP CONSTRAINT KT01_Beleg_InEx_01_HBS_FK;

ALTER TABLE KT01_KT06_Ausgl_InEx_01_LBS DROP CONSTRAINT KT01_KT06_Ausgl_InEx_01_LBS_FK;

ALTER TABLE KT01_KT06_Ausgleich_BL DROP CONSTRAINT KT01_KT06_Ausgl_BL_BelegPos_FK;

ALTER TABLE KT01_KT06_Ausgleich_BL DROP CONSTRAINT KT01_KT06_Ausgl_BL_Beleg_FK;

ALTER TABLE KT06_BelegPosition_InEx_01_WBS DROP CONSTRAINT KT06_BelegPos_InEx_01_WBS_FK;

ALTER TABLE KT06_BelegPosition_KT01_BW DROP CONSTRAINT KT06_BelegPosition_KT01_BW_FK;

ALTER TABLE KT01_Beleg_BH DROP CONSTRAINT KT01_Beleg_BH_PK;

ALTER TABLE KT01_Beleg_InEx_01_HBS DROP CONSTRAINT KT01_Beleg_InEx_01_HBS_PK;

ALTER TABLE KT01_KT06_Ausgl_InEx_01_LBS DROP CONSTRAINT KT01_KT06_Ausgl_InEx_01_LBS_PK;

ALTER TABLE KT01_KT06_Ausgleich_BL DROP CONSTRAINT KT01_KT06_Ausgl_BL_PK;

ALTER TABLE KT06_BelegPosition_InEx_01_WBS DROP CONSTRAINT KT06_BelegPos_InEx_01_WBS_PK;

ALTER TABLE KT06_BelegPosition_KT01_BW DROP CONSTRAINT KT06_BelegPosition_KT01_BW_PK;

DROP INDEX KT01_Beleg_InEx_01_HBS_FK_IDX;

DROP INDEX KT01_Beleg_InEx_01_HBS_Hist_I;

DROP INDEX KT01_KT06_Ausgl_BL_FK_KT01_I;

DROP INDEX KT01_KT06_Ausgl_BL_FK_KT06_I;

DROP INDEX KT01_KT06_Ausgl_BL_Ladat_IDX;

DROP INDEX KT01_KT06_Ausgl_InEx_01_FK_IDX;

DROP INDEX KT01_KT06_Ausgl_InEx_01_Hist_I;

DROP INDEX KT06_BelPos_InEx_01_WBS_FK_IDX;

DROP INDEX KT06_BelPos_InEx_01_WBS_Hist_I;

DROP INDEX KT06_BelegPosition_KT01_BW_IDX;

DROP INDEX KT06_BelegPosition_Ladat_IDX;

DROP TABLE KT01_Beleg_BH;

DROP TABLE KT01_Beleg_InEx_01_HBS;

DROP TABLE KT01_KT06_Ausgl_InEx_01_LBS;

DROP TABLE KT01_KT06_Ausgleich_BL;

DROP TABLE KT06_BelegPosition_InEx_01_WBS;

DROP TABLE KT06_BelegPosition_KT01_BW;

