--<ScriptOptions statementTerminator=";"/>
-- Version 8362

ALTER TABLE ER01_ER03_Kundenprozess_BL DROP CONSTRAINT ER01_ER03_Kundenpr_BL_ER01_FK;

ALTER TABLE ER01_ER03_Kundenprozess_BL DROP CONSTRAINT ER01_ER03_Kundenpr_BL_ER03_FK;

ALTER TABLE ER01_Schaden_SHUKR_02_HBS DROP CONSTRAINT ER01_Schaden_SHUKR_02_HBS_FK;

ALTER TABLE ER03_GerVerf_Schaden_R_01_HBS DROP CONSTRAINT ER03_GerVerf_Sch_R_01_HBS_FK;

ALTER TABLE ER01_ER03_Kundenprozess_BL DROP CONSTRAINT ER01_ER03_Kundenprozess_BL_PK;

ALTER TABLE ER01_Schaden_SHUKR_02_HBS DROP CONSTRAINT ER01_Schaden_SHUKR_02_HBS_PK;

ALTER TABLE ER03_GerVerf_Schaden_R_01_HBS DROP CONSTRAINT ER03_GerVerf_Sch_R_01_HBS_PK;

ALTER TABLE ER03_Gerichtsverfahren_BH DROP CONSTRAINT ER03_Gerichtsverfahren_BH_PK;

DROP TABLE ER01_ER03_Kundenprozess_BL;

DROP TABLE ER01_Schaden_SHUKR_02_HBS;

DROP TABLE ER03_GerVerf_Schaden_R_01_HBS;

DROP TABLE ER03_Gerichtsverfahren_BH;

